### ISSUE TITLE
Add alias to ICommandSelectParamOptions to be able to set alias to mimic command and others

### ISSUE THREAD

**Issue by Mrgaton** [Fortnite-LobbyBot/Pragmatic#51]
![imagen](https://github.com/user-attachments/assets/cf571377-a754-44a3-a403-161e766a6c8b)

**Comment by Mrgaton** [comment]
And aply it to newitems and similar commands

![imagen](https://github.com/user-attachments/assets/f1578d81-53da-4397-865e-864dd451ab66)

**Comment by tnfAngel** [comment]
LGTM
